#version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.develop
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
